// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adgocxwgybjulevrrerp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ29jeHdneWJqdWxldnJyZXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTM4MjIsImV4cCI6MjA1MjUyOTgyMn0.wIvsEA6SUiDBG1EZ7ApGPjdfHkIaQZ8hUzOVLdEYIMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);